#!/bin/bash

export PYTHONPATH=.

function runLocal {
	export TST_LOCATION=local
	export TST_PLATFORM=linux
	export TST_BROWSER=chrome
	#--- export TST_BROWSER=firefox ---#
    nosetests --stop -v $1 
}

# runLocal test_DataInputs.py:testDS.test01_data_struct
#--- runLocal test_addons.py:test_addons.test04_rt_arrow ---#
#--- runLocal "test_Masks:testMasks.test18_HHMM_AM_chk_bad_paste" ---#
#--- runLocal "test_Masks.py:testMasks.test10_YMD_bad_day_2" ---#
#--- runLocal "test_Masks:testMasks.test22_cc_exp_invalid_mon" ---#
#--- runLocal "test_Masks:testMasks.test07_YMD_bad_mon" ---#
#--- runLocal "test_Masks:testMasks.test20_phone_num_paren" ---#
#--- runLocal "test_Masks:testMasks.test03_mask_valid" ---#
#--- runLocal "test_Masks:testMasks.test20_phone_num_paren" ---#
#--- runLocal "test_Masks:testMasks.test21_bot_ac_and_mask" ---#
#--- runLocal "test_Masks:testMasks.test02_mask_error" ---#
#--- runLocal "test_Masks:testMasks.test10_YMD_bad_day_2" ---#
#--- runLocal "test_bootstrap.py:test_bootstrap.test02_bs" ---#
#--- runLocal sauce "safari" "OS X 10.10" "Safari test" test/test_Rocker:test_rocker.test02_rocker ---#
#--- runLocal "test_Rocker.py:test_rocker.test02_rocker" ---#
#--- runLocal "test_Rocker.py:test_rocker.test02_rocker" ---#
#--- runLocal "test_addons.py:test_addons" ---#
#--- runLocal "test_Menus.py:testMO.test07_google" ---#
#--- runLocal "test_Menus.py:testMO.test09_mousefiltering" ---#
# runLocal "test_Menus.py:testMO.test12_replace_window"
# runLocal "test_Menus.py:testMO.test02_js"
#--- runLocal "test_Menus.py:testMO.test03_google" ---#
#--- runLocal "test_set_value.py:test_set_vals" ---#
#--- runLocal "test_SelectList.py:testSL.test08_tab_with_data" ---#
#--- runLocal "test_SelectList.py:testSL.test12_check_bad_paste_autocompl_only" ---#
#--- runLocal "test_SelectList.py:testSL.test13_check_backspace" ---#
#--- runLocal "test_SelectList.py:testSL.test04_regexp" ---#
# runLocal "test_SelectList.py:testSL.test03_autocomplete"
#--- runLocal "test_SelectList.py:testSL.test05_select_w_imgs" ---#
runLocal "test_Money:testMoney.test02_click_pos"
#--- runLocal "test_Money:testMoney.test03_after_entry_pos" ---#
#--- runLocal "test_Money:testMoney" ---#
#--- runLocal "test_Masks:testMasks" ---#
#--- runLocal "test_SelectList.py:testSL.test08_tab_with_data" ---#
#--- runLocal "test_SelectList.py" ---#
#--- runLocal test_addons.py:test_addons.test03_down_arrow ---#
#--- runLocal test_addons.py:test_addons.test06_disable_code ---#
#--- runLocal test_scroll.py ---#
#--- runLocal test_SelectList.py ---#
#--- runLocal test_Rocker.py ---#
#--- runLocal test_set_value.py ---#
sleep 1
kill -TERM -$(pgrep -o runner)
