                'FixedLen' : 12,
                'fmt_initial' : function( val, obj ) { obj._initial_MdY({ mask: this }); }, 
                'Help': 'Mon DD, YYYY',
                'hotkey' : { 1: function( val, obj ) { return obj._date_hotkeys({'val': val,'ofs':1, 'fmt': 'MdY'}); },
                             2: function( val, obj ) { return obj._date_hotkeys({'val': val,'ofs':2, 'fmt': 'MdY'}); } },
                'valid' : { 1: function( val, obj ) { return obj._is_char_valid(val,'JFMASOND',obj._cfg.inv_mon, 'one_char',0); },
                            2: function( val, obj ) { return obj._is_char_valid(val.substring(0,2),
                                                      $.map(obj._cfg.mon_ary, function(obj) { return obj.substring(0,2); }).join('|'),obj._cfg.inv_mon, 'string', 0); },
                            3: function( val, obj ) { return obj._is_char_valid(val.substring(0,3),obj._cfg.mon_ary.join('|'),obj._cfg.inv_mon, 'string', 0); },
                            5: function( val, obj ) { return obj._get_days(val,'MdY'); },
                            6: function( val, obj ) { return obj._get_days(val,'MdY'); },
                            9: { max_val: 9 },
                            10: { max_val: 9 },
                            11: { max_val: 9 },
                            12: { max_val: 9 } },
                'consts' : { 4: ' ', 7:',', 8:' '},
                'Whole' : function( val, obj ) { return obj._get_days(val,'MdY'); }
