                'MaxLen' : 14,
                'Help': '(999) 999-9999',
                'valid' : { 2: { max_val: 9 },
                            3: { max_val: 9 },
                            4: { max_val: 9 },
                            7: { max_val: 9 },
                            8: { max_val: 9 },
                            9: { max_val: 9 },
                            11: { max_val: 9 },
                            12: { max_val: 9 },
                            13: { max_val: 9 },
                            14: { max_val: 9 } },
                'consts' : { 1: '(', 5:')', 6:' ', 10:'-'},
                'Whole' : '^\\([0-9]{3}\\) [0-9]{3}-[0-9]{4}$'
